const MACHINESDATA = [
    {
        id: 1,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 10120232,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 2,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 3,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
    {
        id: 4,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 1012023,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 5,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 6,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
    {
        id: 7,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 1012023,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 8,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 9,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
    {
        id: 10,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 1012023,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 11,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 13,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
    {
        id: 14,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 1012023,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 22,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 23,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
    {
        id: 21,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 1012023,
        movement: "12-12-2024",
        location: " Burgas",
        partner: "1-Bulgaria OOD",
    },
    {
        id: 25,
        model: "LB951",
        brand: "Lavazza",
        serialNumber: 2023031,
        movement: "1-11-2024",
        location: " Plovid",
        partner: "1-Slav OOD",
    },
    {
        id: 31,
        model: "X3",
        brand: "Coffetek",
        serialNumber: 60043320,
        movement: "12-1-2025",
        location: " Sl. brqg",
        partner: " Synu skay OOD",
    },
];

export default MACHINESDATA;
