const MOVEMENTS = [
    {
        machineId: 1,
        id: 1012,
        date: "2025-01-21",
        location: "Aheloy, str Pliska 12",
        partner: "Gedabo LTD",
        object: "Sklad",
        contact: "Ivan Petrov",
        phone: "0897473091",
    },
    {
        machineId: 2,
        id: 1012,
        date: "2025-01-21",
        location: "Aheloy, str Pliska 12",
        partner: "Gedabo LTD",
        object: "Sklad",
        contact: "Ivan Petrov",
        phone: "0897473091",
    },
    {
        machineId: 1,
        id: 1012,
        date: "2025-01-21",
        location: "Aheloy, str Pliska 12",
        partner: "CSB LTD",
        object: "Shop",
        contact: "Dariq Tylieva",
        phone: "0886666444",
    },
    {
        machineId: 2,
        id: 1012,
        date: "2025-01-21",
        location: "Aheloy, str Pliska 12",
        partner: "CSB LTD",
        object: "Shop",
        contact: "Dariq Tylieva",
        phone: "0886666444",
    },
    {
        machineId: 1,
        id: 1012,
        date: "2025-01-21",
        location: "Sozopol, str Shipka 12",
        partner: "SynSAn LTD",
        object: "Hotel",
        contact: "Ivan Georgiev",
        phone: "0987654321",
    },
];

export default MOVEMENTS;
